### ISSUE TITLE
Kafka consumer service problem

### ISSUE THREAD

**Issue by carloselpapa10** [xstefank/eventuate-sagas#3]
Hi @xstefank 
I wanna know whether you could resolve the problem with kafka consumer service "Commit cannot be completed since the group has already rebalanced and assigned the partitions to another member. This means ...."

If so, how did u do that.

Appreciate it

**Comment by xstefank** [comment]
hi @carloselpapa10 how did you run into this error? If I can reproduce it locally I will take a look. I don't remember seeing it before.

**Comment by carloselpapa10** [comment]
@xstefank I meant a question you did through the eventuate tram framework git hub issue. By the way, the error was fixed by updating the eventuate tram version on the project. You question was valuable for us.. Thank You.

**Comment by carloselpapa10** [comment]
just to see what I mean
https://github.com/eventuate-local/eventuate-local/issues/44

**Comment by xstefank** [comment]
@carloselpapa10 agh, I forgot about that one :) Thanks a lot for the reminder! I will update the version here.
